### ISSUE TITLE
add "related services" to schema

### ISSUE THREAD

**Issue by KevinField** [stepping-stone/ldap-schemas#2]
It would enable a lot of automation to replace Kunden.ods with an LDAP-integrated application, starting with associating related services with one another.  E.g. from the product UID for a KVM server you should be able to derive the product UID for the customer mail account, backup account, maintenance package, monitoring package, etc., but also in both directions.  (E.g. if I have a customer mail account, I should be able to find the KVM server it goes with, from which I can find any of the other services.)

**Comment by meichenberger** [comment]
The application is in doing ...

What you would like to have, is not possible, as the orders of the different products / services don't all come at the same time and in the same order ...

Please remember, that this is a non-private issue tracker.
